language: haskell
cache:
  directories:
    - tests/elm-stuff/build-artifacts
install:
  - npm install -g elm elm-test
  - elm-package install -y
  - cd tests && elm-package install -y && cd ../
script: elm-test
